### ISSUE TITLE
Change <index not found> to <item not found> in diff output

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-support#2]
And "index not to exist" to "item not to exist"

https://github.com/bethesque/pact-support/blob/master/lib/pact/matchers/unexpected_index.rb
https://github.com/bethesque/pact-support/blob/master/lib/pact/matchers/index_not_found.rb

**Comment by bethesque** [comment]
Done, not released.

**Comment by tancnle** [comment]
@bethesque should this be closed?

**Comment by bethesque** [comment]
🤔 Can't remember what was going on with this issue!
