### ISSUE TITLE
SomethingLike can now make one parent rule, instead of a rule for each child.

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-support#34]
SomethingLike.new(top_thing: {foo: "bar", wiffle: "meep"}) should generate one rule for top_thing, not a rule each for foo and wiffile.

**Comment by bethesque** [comment]
```ruby
it "recreates the same object hierarchy", pending: 'Waiting for Pact JVM to implement nested type matching' do
```

@uglyog I've just discovered a relic of the past in the way the ruby impl is writing the matching rules. Back in the day, when we were first writing the v2 spec, the jvm implementation initially didn't support rule inheritance (ie. if a hash is marked as match:type, then all the children should also be match:type as well). So I wrote the ruby rule code to make a rule for each key, with the intent to change it once the jvm supported inheritance. A long time has passed, and I had completely forgotten about it until @neilcampbell asked me a question while he was experimenting with wrapping the ruby mock service.

I'm updating the code now, and just wanted to make sure we're on the same page with this! Can you review this and make sure it fits with what you expect? https://github.com/pact-foundation/pact-support/blob/2ba49b648d35f0ccab752f8512aaaae3c3edda95/spec/lib/pact/matching_rules/extract_spec.rb

**Comment by uglyog** [comment]
Just FYI, It does cascade the matchers and I documentation the matching implementation in the JVM here https://github.com/DiUS/pact-jvm/wiki/Matching

**Comment by uglyog** [comment]
Slight difference (functionally the same), the JVM generates 

```json
{
              "$.body.alligators" => {"match" => "type", "min" => 1},
              "$.body.alligators[*].*" => {"match" => "type"}
}
```

for https://github.com/pact-foundation/pact-support/blob/2ba49b648d35f0ccab752f8512aaaae3c3edda95/spec/lib/pact/matching_rules/extract_spec.rb#L112

**Comment by uglyog** [comment]
Should the matcher for https://github.com/pact-foundation/pact-support/blob/2ba49b648d35f0ccab752f8512aaaae3c3edda95/spec/lib/pact/matching_rules/extract_spec.rb#L174 be

```ruby
{
              "$.query.bar" => {"match" => "regex", "regex" => "foo"}
}
```
?
