### ISSUE TITLE
Missing requires for Pact::Reification and Pact::Request

### ISSUE THREAD

**Issue by mdub** [pact-foundation/pact-support#36]
I'm using `pact-support` directly, in RSpec, with the following matcher:

```ruby
require "pact/matchers"
require "pact/matchers/unix_diff_formatter"
require "term/ansicolor"

RSpec::Matchers.define :match_data do |_expected|

  match do |actual|
    difference(actual).empty?
  end

  failure_message do |actual|
    diff = difference(actual)
    formatted_diff = Pact::Matchers::UnixDiffFormatter.call(diff, :colour => true)
    colorize(formatted_diff)
  end

  def difference(actual)
    diff(expected, actual)
  end

  def colorize(s)
    s.split("\n").collect do |line|
      ::Term::ANSIColor.reset + line
    end.join("\n")
  end

  include Pact::Matchers

end
```

With the release of `pact-support 1.1.0`, I find I have to explicitly include `Pact::Reification` and `Pact::Request`, with:

```ruby
require "pact/reification"
require "pact/shared/request"
```

Could these be included from the modules that use them?

**Comment by bethesque** [comment]
I'll fix that ASAP.

**Comment by bethesque** [comment]
I've released 1.1.1 with those extra requires.
I've added `require "pact/shared/request"` but I can't see what it's needed for. What's the stacktrace when that's missing?

**Comment by mdub** [comment]
Thanks @bethesque.

Without `pact/shared/request`, I get an error out of `pact/reification`:

```
     NameError:
       uninitialized constant Pact::Request
     # /Users/mike_williams/.gem/ruby/2.4.1/gems/pact-support-1.1.0/lib/pact/reification.rb:19:in `from_term'
     # /Users/mike_williams/.gem/ruby/2.4.1/gems/pact-support-1.1.0/lib/pact/reification.rb:18:in `block in from_term'
     # /Users/mike_williams/.gem/ruby/2.4.1/gems/pact-support-1.1.0/lib/pact/reification.rb:18:in `map'
     # /Users/mike_williams/.gem/ruby/2.4.1/gems/pact-support-1.1.0/lib/pact/reification.rb:18:in `from_term'
```

I'm afraid 1.1.1 looks a bit borked; I see errors when requiring `pact/matchers`:

```
NameError:
  uninitialized constant Pact::Matchers
  Did you mean?  MatchData
# /Users/mike_williams/.gem/ruby/2.4.1/gems/pact-support-1.1.1/lib/pact/consumer_contract/query_hash.rb:10:in `<class:QueryHash>'
# /Users/mike_williams/.gem/ruby/2.4.1/gems/pact-support-1.1.1/lib/pact/consumer_contract/query_hash.rb:7:in `<module:Pact>'
# /Users/mike_williams/.gem/ruby/2.4.1/gems/pact-support-1.1.1/lib/pact/consumer_contract/query_hash.rb:6:in `<top (required)>'
# /Users/mike_williams/.gem/ruby/2.4.1/gems/pact-support-1.1.1/lib/pact/consumer_contract/query.rb:1:in `require'
# /Users/mike_williams/.gem/ruby/2.4.1/gems/pact-support-1.1.1/lib/pact/consumer_contract/query.rb:1:in `<top (required)>'
# /Users/mike_williams/.gem/ruby/2.4.1/gems/pact-support-1.1.1/lib/pact/shared/request.rb:4:in `require'
# /Users/mike_williams/.gem/ruby/2.4.1/gems/pact-support-1.1.1/lib/pact/shared/request.rb:4:in `<top (required)>'
# /Users/mike_williams/.gem/ruby/2.4.1/gems/pact-support-1.1.1/lib/pact/matchers/matchers.rb:6:in `require'
# /Users/mike_williams/.gem/ruby/2.4.1/gems/pact-support-1.1.1/lib/pact/matchers/matchers.rb:6:in `<top (required)>'
# /Users/mike_williams/.gem/ruby/2.4.1/gems/pact-support-1.1.1/lib/pact/matchers.rb:1:in `require'
# /Users/mike_williams/.gem/ruby/2.4.1/gems/pact-support-1.1.1/lib/pact/matchers.rb:1:in `<top (required)>'
# ./spec/support/matchers.rb:2:in `require'
```

**Comment by bethesque** [comment]
Can you try requiring 'pact/support'?

**Comment by bethesque** [comment]
I've released 1.1.2, try again.

**Comment by bethesque** [comment]
While you're here, what do you think about the new "list of differences" that comes with the diff?

**Comment by mdub** [comment]
1.1.2 fixed _those_ "require" errors, @bethesque, but I hit another while trying to check out the "list of differences" you mentioned.  I intentionally introduced a test failure, thinking, but UnixDiffFormatter seemed unhappy:

```
NoMethodError: undefined method `configuration' for Pact:Module
# /Users/mike_williams/.gem/ruby/2.4.1/gems/pact-support-1.1.2/lib/pact/matchers/unix_diff_formatter.rb:24:in `call'
# ./spec/support/matchers.rb:14:in `block (2 levels) in <top (required)>'
# ./spec/features/aws/auto_scaling/cloudwatch_triggers_spec.rb:157:in `block (3 levels) in <top (required)>'
```

Adding `require "pact/configuration"` fixed it. And, I get the following extra info in the test failure. 

> Description of differences    
> --------------------------------------
> * Could not find key "cpuAlarm57a5478bxxx" (keys present are: instancesSecurityGroup, iamRole, iamInstanceProfile, autoScalingGroup, launchConfiguration, asgScalingPolicy57a5478b, cpuAlarm57a5478b) at $.Resources

Nice.

Hey, what do you think about including some form of my `:match_data` RSpec matcher in `pact-support` itself?

**Comment by bethesque** [comment]
I'll add the missing require. Even though I have used just the matchers
file before, it's really designed to be used by requiring the pact/support
entry point.

Yes, great idea, I'll add that matcher to the gem.

**Comment by mdub** [comment]
> it's really designed to be used by requiring the pact/support

Ah, right. That's good to know.

> I'll add that matcher to the gem.

Excellent!

**Comment by bethesque** [comment]
Try this: https://rubygems.org/gems/rspec-pact-matchers

**Comment by mdub** [comment]
"rspec-pact-matchers" works a treat; thanks @bethesque!

**Comment by bethesque** [comment]
NP. Let me know if you think it needs the "actual" in there as well as the diff (as the HTTP pact output does).
