### ISSUE TITLE
Randexp error using like_datetime in a structure that's missing from the provider response

### ISSUE THREAD

**Issue by lsimoneau** [pact-foundation/pact-support#44]
We had a pact with a response body including:

```
'action_history' => [
  {
    'type' => 'PURCHASED',
    'at' => Pact.like_datetime('2016-02-11T12:00:00Z')
  }
],
```

The `action_history` field was renamed to `events` in the provider, and the pact failed with:

```
     Failure/Error: expect(response_body).to match_term expected_response_body, diff_options

     RuntimeError:
       Sorry, "[+" is too vague, try setting a range: "[{1,3}"
```

I've tested this with:

* pact 1.14.0 and pact-support 1.1.5
* pact 1.15.0 and pact-support 1.1.7

**Comment by bethesque** [comment]
Thanks for raising, I will investigate.

**Comment by bethesque** [comment]
Please update to pact 1.16.0.

**Comment by bethesque** [comment]
Still getting during `bundle exec rake pact:verify:foobar_using_broker:fail`

pact "1.19.1", pact-support (1.2.4)

**Comment by bethesque** [comment]
Can you please recreate the issue using this repository? https://github.com/pact-foundation/pact-ruby-e2e-example

**Comment by YOU54F** [comment]
randexp gem was removed as a dependency in https://github.com/pact-foundation/pact-support/pull/91
