### ISSUE TITLE
Remove warning log message

### ISSUE THREAD

**Issue by neilcampbell** [pact-foundation/pact-support#45]
When using a min type matcher, the following warning is output.
`WARN: Ignoring unsupported matching rules {"min"=>1} for path $['body']['values']`

The pact verification however works as expected and no rules are ignored.

See https://github.com/SEEK-Jobs/pact-net/issues/112 for details.

**Comment by bethesque** [comment]
I believe this is fixed now! Sorry it's taken so long :( :( :( Please update to the latest standalone.
