### ISSUE TITLE
Proxy error

### ISSUE THREAD

**Issue by mickehl** [pact-foundation/pact-support#66]
https://github.com/pact-foundation/pact-support/blob/be6d29cbe37cb1559aff787f17a9da78f173927b/lib/pact/consumer_contract/pact_file.rb#L84

Using a proxy I'm getting a "Network is unreachable" when executing pact-provider-verifier. When adding :ENV as a parameter here it works.

**Comment by bethesque** [comment]
Could you open a PR for this please @mickehl? I'll be happy to merge it.

**Comment by bethesque** [comment]
Did it while waiting for build. It's in version `1.10.2`. Do you need a release of any of the packages that use it (pact-ruby-standalone) or are you using the ruby gem directly?

**Comment by mickehl** [comment]
I use pact-provider-verifier from pact-ruby-standalone.

**Comment by bethesque** [comment]
Ok, I've released `1.65.0` of the pact-ruby-standalone.
