### ISSUE TITLE
Ordering in body response..

### ISSUE THREAD

**Issue by akbhartiya** [pact-foundation/pact-support#74]
My response body looks like
"body": {
          "currentPage": 1,
          "resultsPerPage": 26,
          "totalPages": 1,
          "totalResults": 1,
          "courses": [
            {
              "id": "",
              "name": "Ruby",
              "description": ""
            },
            {
              "id": "",
              "name": "Java",
              "description": ""
            },
            {
              "id": "",
              "name": "C++",
              "description": ""
            },
            {
              "id": "",
              "name": "C",
              "description": ""
            },
            {
              "id": "",
              "name": "DotNet",
              "description": ""
            }
          ]
        }
How i can ensure that **courses** array contains sorted record or not based on Name field. In other word, rest service returning courses item in ascending order based on Name field.

Thanks

**Comment by bethesque** [comment]
That sounds more like a functional test, not a contract test. Please read https://docs.pact.io/best_practices/consumer/contract_tests_not_functional_tests and https://docs.pact.io/best_practices/provider/using_provider_states_effectively

From a consumer perspective, it's your job to make sure you're using the right parameters in the query. It's the provider's job to make sure sure that the items are sorted according to the parameters you've given it.
