### ISSUE TITLE
Query parsing produces incorrect query in pact for array parameters

### ISSUE THREAD

**Issue by wspurgin** [pact-foundation/pact-support#83]
# Pre issue-raising checklist

I have already (please mark the applicable with an `x`):

* [x] Upgraded to the latest version of the relevant libraries
* [x] Checked to see if the issue has already been raised
* [x] Created an executable example that demonstrates the issue using either:
  * a Dockerfile
  * a fork of https://github.com/pact-foundation/pact-ruby-standalone-e2e-example
  * a Git repository with a Travis or Appveyor (or similar) build
  * a gist with all the relevant code and full instructions on how to run it
  * (specifically this recration repo: https://github.com/wspurgin/vanilla)

## Software versions

* **pact-support:** pact gem `1.55.6`
* **pact-ruby-standalone** (if relevant):
* **OS**: Mac OSX 10.14.6

## Expected behaviour

I expected query parsing behavior to not break pacts when upgrading a minor version of `pact-support`.

## Actual behaviour

Because of the query parsing behavior added in `1.15.2` and used now on consumer side pact production as of `1.16.4`, the query parsing of array based query parameters produces different pact files (and causes pact verification to fail as a result).

Consumer pact produced with pact-support at [`1.15.1`](https://github.com/wspurgin/vanilla/blob/master/spec/pacts/consumer_service-producer_service.pact-support-1.15.1.json#L15) then [passes verification](https://github.com/wspurgin/vanilla/runs/1409198834?check_suite_focus=true) as expected.

Consumer pact produced with pact-support at [`1.16.4`](https://github.com/wspurgin/vanilla/blob/master/spec/pacts/consumer_service-producer_service.json#L15) then [fails verification](https://github.com/wspurgin/vanilla/runs/1409250638?check_suite_focus=true)

## Steps to reproduce

I made this Git Repo: https://github.com/wspurgin/vanilla to showcase how pacts go from passing to failing

Nothing to special when it comes to [the interaction](https://github.com/wspurgin/vanilla/blob/master/spec/service_providers/producer_service_spec.rb#L25-L44) - just that its an array parameter. Verification of the pact is in the same repo (setup [here](https://github.com/wspurgin/vanilla/blob/master/spec/service_consumers/pact_helper.rb) where you can switch between the 1.15.1 and 1.16.4 version of the pact)

## Relevent log files

I've included the logs from [this failure run](https://github.com/wspurgin/vanilla/actions/runs/368275216) 

[test.log](https://github.com/pact-foundation/pact-support/files/5554093/test.log)
[producer_mock_service.log](https://github.com/pact-foundation/pact-support/files/5554095/producer_mock_service.log)
[pact.log](https://github.com/pact-foundation/pact-support/files/5554096/pact.log)

Specifically is the pact verification logs in `test.log`:
```
Started GET "/things?ids=12345&ids=67890" for 127.0.0.1 at 2020-11-17 03:09:18 +0000
Processing by ThingsController#index as HTML
  Parameters: {"ids"=>"67890"}
Unpermitted parameter: :ids
Completed 400 Bad Request in 4ms (ActiveRecord: 0.0ms | Allocations: 424)
   (0.0ms)  rollback transaction
   (0.1ms)  begin transaction
Started GET "/things?ids=12345&ids=67890" for 127.0.0.1 at 2020-11-17 03:09:18 +0000
Processing by ThingsController#index as HTML
  Parameters: {"ids"=>"67890"}
Unpermitted parameter: :ids
Completed 400 Bad Request in 1ms (ActiveRecord: 0.0ms | Allocations: 319)
   (0.0ms)  rollback transaction
```

You can see the absence of the brackets `[]` makes the `ids` parameter be treated as a singular argument and turned into a hash `{ "ids" => "67890" }`.

I will say that the Producer Mock Service looks like it gets _two_ requests. One that _does_ have the right `[]` notation in the query params, and a second that does not... but the registered interaction looks like it's registered with the param sans the brackets (fwiw)

**Comment by bethesque** [comment]
Please update to the latest pact-support version and let me know how you go. 

https://github.com/pact-foundation/pact-support/commit/12105ddde458185d70f86e58fba54c51b669638a

**Comment by wspurgin** [comment]
Thanks @bethesque Looks to have worked https://github.com/wspurgin/vanilla/actions/runs/402783867 🎉
