### ISSUE TITLE
feat: update to support for Ruby 3.0

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-support#87]
Have updated ActiveSupportSupport, but build is still failing because of awesome_print

https://github.com/pact-foundation/pact-support/runs/1739779619?check_suite_focus=true#step:5:1428

It seems that the [issue](https://github.com/awesome-print/awesome_print/issues/382) is being worked on and hopefully a fix will be out soon.

**Comment by annapetry** [comment]
Hello! I found this issue via [this PR](https://github.com/pact-foundation/pact-support/pull/85), which outlines an issue I am also experiencing.  It looks like the awesome-print blocker mentioned in the description [has been resolved as of Jan 25](https://github.com/awesome-print/awesome_print/issues/382). Is there anything I can do to help move this issue forward?

**Comment by bethesque** [comment]
It looks like it's working already https://github.com/pact-foundation/pact-support/runs/2879849663?check_suite_focus=true

There shouldn't be anything you need to do for the pact-support gem, as the awesome-print dependency update is a minor version update. Bundle update in your project should make it work. Have you found otherwise?
