### ISSUE TITLE
LoadError: cannot load such file -- expgen (1.16.9)

### ISSUE THREAD

**Issue by alexcameron89** [pact-foundation/pact-support#92]
Hey everyone, 👋 

I am seeing a new error from the most recent patch version (1.16.9) when running the pacts through Rspec:
```
LoadError:
  cannot load such file -- expgen
```

It seems to be related to this PR: https://github.com/pact-foundation/pact-support/pull/91

I noticed that the `expgen` is required in a file, but it is only labeled as a development_dependency.

When explicitly adding `expgen` to my Gemfile, the error disappears.

**Comment by bethesque** [comment]
Thanks. I'll get that fixed.

**Comment by bethesque** [comment]
That new release is out. Sorry about that. I accepted a PR yesterday to replace the randexp gem with the expgen gem, and I didn't look closely enough at the require line.
